language: python
service:
- postgresql
os:
- linux
python:
- '3.6'
- 3.7-dev
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
install:
- pip install -r requirements/development.txt
- pip install -r requirements/test.txt
before_script:
- openssl aes-256-cbc -K $encrypted_51f2620d1008_key -iv $encrypted_51f2620d1008_iv
  -in .secrets.tar.enc -out .secrets.tar -d
- tar xvf .secrets.tar
- psql -c 'CREATE DATABASE littera_db;' -U postgres
- psql -c 'CREATE USER littera_admin;' -U postgres
script:
- pytest
