version: '3.7'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
     - '5432:5432'
    volumes:
     - ./pgdata:/usr/src
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python3 src/main.py --host=0.0.0.0 --port=8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db

